name: Build and Test

on:
  push:
    branches: [ s3nj23-dev ]
  pull_request:
    branches: [ s3nj23-dev ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Node.Js
        uses: actions/setup-node@v3
        with:
          node-version: '18.10.0'

      - name: Install node modules
        run: npm install

      - name: Run build 
        run: npm run build
       
  
        
        

  
        
        
